import React, { useMemo, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Check, CircleDollarSign, Gift, Star, UsersRound } from 'lucide-react-native';
import { Badge, Button, Card, Dialog, EmptyState, Field, Progress, SectionHeader, StatCard, Table } from '../components/ui';
import { colors, money, radii } from '../theme';
import { useDemo } from '../store/DemoStore';

export function BenefitsScreen() {
  const { state, persona, toggleBenefit } = useDemo();
  const [selectedEmployee, setSelectedEmployee] = useState(persona?.employeeId ?? 'EMP-2026-001');
  const employee = state.employees.find((item) => item.id === selectedEmployee) ?? state.employees[0];
  const totalEmployee = employee.benefitPlanIds.reduce((sum, id) => sum + (state.benefits.find((plan) => plan.id === id)?.employeeCents ?? 0), 0);
  const totalEmployer = state.benefits.reduce((sum, plan) => sum + plan.employerCents * plan.enrolledCount, 0);
  return <>
    <View style={styles.stats}><StatCard label="Benefit plans" value={String(state.benefits.length)} detail="Health, insurance, allowance" icon={Gift} /><StatCard label="Total enrollments" value={state.benefits.reduce((sum, plan) => sum + plan.enrolledCount, 0).toLocaleString()} detail="Across active plans" icon={UsersRound} tone="success" /><StatCard label="Employer monthly cost" value={money(totalEmployer)} detail="Fictional aggregate" icon={CircleDollarSign} tone="warning" /><StatCard label="Selected employee share" value={money(totalEmployee)} detail="Feeds payroll preview" icon={CircleDollarSign} tone="info" /></View>
    {persona?.role === 'hr' ? <Card style={styles.pad}><SectionHeader title="Enrollment workbench" subtitle="Enter an employee ID to manage eligible plans. Duplicate enrollment is prevented by the toggle state." /><View style={styles.employeePicker}><Field label="Employee ID" value={selectedEmployee} onChangeText={setSelectedEmployee} /><View style={{ flex: 2 }}><Text style={styles.employeeName}>{employee.firstName} {employee.lastName}</Text><Text style={styles.muted}>{employee.department} · {employee.employmentType}</Text></View></View></Card> : null}
    <View style={styles.planGrid}>{state.benefits.map((plan) => { const enrolled = employee.benefitPlanIds.includes(plan.id); return <Card key={plan.id} style={styles.plan}><View style={styles.rowBetween}><View style={styles.planIcon}><Gift size={17} color={colors.blue} /></View><Badge label={plan.category} tone="info" /></View><Text style={styles.planTitle}>{plan.name}</Text><Text style={styles.muted}>{plan.eligibility}</Text><View style={styles.costs}><View><Text style={styles.costLabel}>Employee</Text><Text style={styles.costValue}>{money(plan.employeeCents)}</Text></View><View><Text style={styles.costLabel}>Employer</Text><Text style={styles.costValue}>{money(plan.employerCents)}</Text></View></View><View style={styles.enrollment}><Text style={styles.enrolledCount}>{plan.enrolledCount} enrolled</Text>{persona?.role === 'hr' ? <Button label={enrolled ? 'Remove enrollment' : 'Enroll employee'} tone={enrolled ? 'danger' : 'primary'} compact onPress={() => toggleBenefit(employee.id, plan.id)} /> : <Badge label={enrolled ? 'Enrolled' : 'Not enrolled'} tone={enrolled ? 'success' : 'neutral'} />}</View></Card>; })}</View>
    <Card><View style={styles.pad}><SectionHeader title="Cost summary" subtitle="Displayed values reconcile to current runtime enrollment counts." /></View><Table headers={['Plan', 'Eligibility', 'Enrolled', 'Employee share', 'Employer share', 'Monthly employer total']} rows={state.benefits.map((plan) => [plan.name, plan.eligibility, String(plan.enrolledCount), money(plan.employeeCents), money(plan.employerCents), money(plan.employerCents * plan.enrolledCount)])} /></Card>
  </>;
}

export function PerformanceScreen() {
  const { state, persona, submitSelfReview, submitManagerReview, acknowledgeReview } = useDemo();
  const [selfText, setSelfText] = useState('I delivered the attendance cleanup milestone and improved response time for internal clients.');
  const [managerText, setManagerText] = useState('Consistent delivery with strong ownership. Continue developing cross-team influence.');
  const [rating, setRating] = useState('4');
  const active = state.performanceCycles.find((cycle) => cycle.status === 'Active')!;
  const completed = state.performanceCycles.find((cycle) => cycle.status === 'Completed')!;
  const scoped = useMemo(() => {
    if (persona?.role === 'employee') return active.participants.filter((p) => p.employeeId === persona.employeeId);
    if (persona?.role === 'manager') return active.participants.filter((p) => state.employees.find((employee) => employee.id === p.employeeId)?.managerId === persona.employeeId);
    return active.participants;
  }, [active.participants, persona, state.employees]);
  const doneSelf = active.participants.filter((p) => !!p.selfReview).length;
  const doneManager = active.participants.filter((p) => !!p.managerReview).length;
  const acknowledged = active.participants.filter((p) => p.acknowledged).length;
  const myParticipant = active.participants.find((p) => p.employeeId === persona?.employeeId);
  const name = (id: string) => { const employee = state.employees.find((item) => item.id === id); return employee ? `${employee.firstName} ${employee.lastName}` : id; };
  return <>
    <View style={styles.stats}><StatCard label="Active cycle" value="1" detail={active.name} icon={Star} /><StatCard label="Self-reviews" value={`${doneSelf}/${active.participants.length}`} detail="Employee stage" icon={Check} tone="info" /><StatCard label="Manager reviews" value={`${doneManager}/${active.participants.length}`} detail="Manager stage" icon={UsersRound} tone="warning" /><StatCard label="Acknowledged" value={`${acknowledged}/${active.participants.length}`} detail="Final employee stage" icon={Check} tone="success" /></View>
    <View style={styles.twoCol}><Card style={styles.pad}><SectionHeader title={active.name} subtitle={`Due ${active.dueDate}`} action={<Badge label="Active" tone="success" />} /><View style={styles.progressStack}><View><View style={styles.rowBetween}><Text style={styles.progressLabel}>Self-review completion</Text><Text style={styles.progressValue}>{Math.round(doneSelf / active.participants.length * 100)}%</Text></View><Progress value={doneSelf / active.participants.length * 100} /></View><View><View style={styles.rowBetween}><Text style={styles.progressLabel}>Manager review completion</Text><Text style={styles.progressValue}>{Math.round(doneManager / active.participants.length * 100)}%</Text></View><Progress value={doneManager / active.participants.length * 100} color={colors.amber} /></View></View></Card><Card style={styles.pad}><SectionHeader title={completed.name} subtitle={`Completed · due ${completed.dueDate}`} action={<Badge label="Completed" tone="neutral" />} /><Text style={styles.completedBig}>4.0</Text><Text style={styles.muted}>Average seeded rating · no automatic compensation or employment action</Text></Card></View>
    {persona?.role === 'employee' ? <Card style={styles.pad}><SectionHeader title="My review task" subtitle="Complete each stage in sequence." /><View style={styles.taskSteps}><Badge label={myParticipant?.selfReview ? 'Self-review submitted' : 'Self-review due'} tone={myParticipant?.selfReview ? 'success' : 'warning'} /><Badge label={myParticipant?.managerReview ? 'Manager review complete' : 'Awaiting manager'} tone={myParticipant?.managerReview ? 'success' : 'neutral'} /><Badge label={myParticipant?.acknowledged ? 'Acknowledged' : 'Acknowledgement pending'} tone={myParticipant?.acknowledged ? 'success' : 'neutral'} /></View>{!myParticipant?.selfReview ? <><Field label="Self-review" multiline value={selfText} onChangeText={setSelfText} /><View style={styles.actions}><Button label="Submit self-review" onPress={() => submitSelfReview(selfText)} /></View></> : myParticipant.managerReview && !myParticipant.acknowledged ? <><Card style={styles.reviewCard}><Text style={styles.detailLabel}>Manager feedback · Rating {myParticipant.rating}/5</Text><Text style={styles.reviewText}>{myParticipant.managerReview}</Text></Card><View style={styles.actions}><Button label="Acknowledge review" icon={Check} onPress={acknowledgeReview} /></View></> : <Text style={styles.muted}>Your current task is complete. Sign in as Line Manager to continue the workflow when applicable.</Text>}</Card> : null}
    {persona?.role === 'manager' ? <Card style={styles.pad}><SectionHeader title="Manager review workbench" subtitle="Only direct reports appear here." />{scoped.length ? scoped.map((participant) => <View key={participant.employeeId} style={styles.reviewRow}><View style={{ flex: 1 }}><Text style={styles.employeeName}>{name(participant.employeeId)}</Text><Text style={styles.muted}>{participant.selfReview || 'Self-review has not been submitted yet.'}</Text></View>{participant.managerReview ? <Badge label={`Completed · ${participant.rating}/5`} tone="success" /> : participant.selfReview ? <Button label="Complete review" onPress={() => submitManagerReview(participant.employeeId, managerText, Number(rating))} /> : <Badge label="Waiting for employee" />}</View>) : <EmptyState title="No direct-report review tasks" body="Only scoped participants appear for the Line Manager." /> }<View style={styles.formRow}><Field label="Feedback used for next review" multiline value={managerText} onChangeText={setManagerText} /><Field label="Rating 1–5" value={rating} onChangeText={setRating} keyboardType="numeric" /></View></Card> : null}
    {persona?.role === 'hr' ? <Card><View style={styles.pad}><SectionHeader title="Participant progress" subtitle="HR visibility across the active cycle." /></View><Table headers={['Employee', 'Self-review', 'Manager review', 'Rating', 'Acknowledged']} rows={active.participants.map((participant) => [name(participant.employeeId), <Badge label={participant.selfReview ? 'Submitted' : 'Due'} tone={participant.selfReview ? 'success' : 'warning'} />, <Badge label={participant.managerReview ? 'Complete' : 'Pending'} tone={participant.managerReview ? 'success' : 'neutral'} />, participant.rating ? `${participant.rating}/5` : '—', <Badge label={participant.acknowledged ? 'Yes' : 'No'} tone={participant.acknowledged ? 'success' : 'neutral'} />])} /></Card> : null}
  </>;
}

const styles = StyleSheet.create({
  stats: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, pad: { padding: 18, gap: 15 }, employeePicker: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-end', gap: 14 }, employeeName: { color: colors.ink, fontSize: 13, fontWeight: '900' }, muted: { color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 3 }, planGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, plan: { minWidth: 250, flex: 1, padding: 16, gap: 9 }, rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 }, planIcon: { width: 34, height: 34, borderRadius: 8, backgroundColor: colors.blueSoft, alignItems: 'center', justifyContent: 'center' }, planTitle: { color: colors.ink, fontSize: 14, fontWeight: '900' }, costs: { paddingVertical: 12, flexDirection: 'row', gap: 30, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.border }, costLabel: { color: colors.muted, fontSize: 9 }, costValue: { color: colors.text, fontSize: 12, fontWeight: '800', marginTop: 3 }, enrollment: { minHeight: 35, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 }, enrolledCount: { color: colors.muted, fontSize: 10, fontWeight: '600' },
  twoCol: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 }, progressStack: { gap: 18 }, progressLabel: { color: colors.text, fontSize: 11, fontWeight: '700' }, progressValue: { color: colors.ink, fontSize: 11, fontWeight: '900' }, completedBig: { color: colors.ink, fontSize: 32, fontWeight: '900' }, taskSteps: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8 }, reviewCard: { padding: 14, backgroundColor: colors.surfaceAlt }, detailLabel: { color: colors.muted, fontSize: 9, fontWeight: '800', textTransform: 'uppercase' }, reviewText: { color: colors.text, fontSize: 12, lineHeight: 18, marginTop: 7 }, reviewRow: { minHeight: 70, flexDirection: 'row', alignItems: 'center', gap: 14, paddingVertical: 10, borderBottomWidth: 1, borderColor: colors.border }, formRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
});
