import React, { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Bell, Check, CloudOff, Code2, DatabaseZap, Mail, RefreshCw, Send, Settings, ShieldCheck, Webhook } from 'lucide-react-native';
import { Badge, Button, Card, EmptyState, SectionHeader, SelectChips, StatCard, Table } from '../components/ui';
import { DEMO_DATE, DEMO_PASSWORD, personas, SEED_VERSION } from '../data/seed';
import { colors, radii } from '../theme';
import { useDemo } from '../store/DemoStore';

export function IntegrationsScreen() {
  const { state, persona, simulateWebhook, simulateGovernmentSubmission } = useDemo();
  const [endpoint, setEndpoint] = useState<'GET /v1/employees/EMP-2026-001' | 'POST /v1/leave-requests'>('GET /v1/employees/EMP-2026-001');
  const connectors = [
    ['Biometric devices', 'Simulated', 'Prepared local event batch; no hardware connection.'],
    ['Email & mobile', 'Simulated', 'Messages appear in Demo Outbox; nothing is sent.'],
    ['Public API', 'Not Connected', 'Local in-process example adapter only.'],
    ['Webhooks', 'Simulated', 'Payload history and retry without outbound calls.'],
    ['Bank payroll', 'File Export Only', 'Labeled CSV; no payment transmission.'],
    ['Accounting journal', 'File Export Only', 'Balanced XLSX; no accounting connection.'],
    ['Government portals', 'Not Connected', 'Labeled files and fictional submission reference.'],
  ];
  const statusTone = (status: string) => status === 'Simulated' ? 'info' : status === 'File Export Only' ? 'warning' : 'neutral';
  return <>
    <Card style={styles.notice}><CloudOff size={18} color={colors.blueDark} /><View style={{ flex: 1 }}><Text style={styles.noticeTitle}>No connector on this page is live</Text><Text style={styles.muted}>Every interaction is local to the in-memory demo. No outbound delivery, device call, payment, or government submission occurs.</Text></View></Card>
    <View style={styles.stats}><StatCard label="Connectors" value="7" detail="Visible demo catalog" icon={DatabaseZap} /><StatCard label="Simulated" value="3" detail="Local behavior only" icon={RefreshCw} tone="info" /><StatCard label="File export only" value="2" detail="Browser-generated outputs" icon={Send} tone="warning" /><StatCard label="Demo Outbox" value={String(state.outbox.length)} detail="No messages sent" icon={Mail} tone="success" /></View>
    <View style={styles.connectorGrid}>{connectors.map(([name, status, detail]) => <Card key={name} style={styles.connector}><View style={styles.connectorIcon}>{name === 'Webhooks' ? <Webhook size={18} color={colors.blue} /> : name.includes('Email') ? <Bell size={18} color={colors.blue} /> : <Settings size={18} color={colors.blue} />}</View><Text style={styles.connectorTitle}>{name}</Text><Badge label={status} tone={statusTone(status)} /><Text style={styles.muted}>{detail}</Text></Card>)}</View>
    <View style={styles.twoCol}><Card style={styles.pad}><SectionHeader title="API Playground" subtitle="Documented examples execute against a local adapter." /><SelectChips options={['GET /v1/employees/EMP-2026-001', 'POST /v1/leave-requests'] as const} value={endpoint} onChange={setEndpoint} /><View style={styles.codeBlock}><Text style={styles.codeText}>{endpoint.startsWith('GET') ? `{\n  "id": "EMP-2026-001",\n  "name": "Mika Santos",\n  "status": "active",\n  "source": "local-demo-adapter"\n}` : `{\n  "status": 201,\n  "requestId": "REQ-WF-DEMO",\n  "workflow": "Pending Manager",\n  "networkRequestMade": false\n}`}</Text></View><Badge label="200 · Local response" tone="success" /></Card>
      <Card style={styles.pad}><SectionHeader title="Webhook Simulator" subtitle={`${state.webhookAttempts} local delivery attempts recorded.`} /><View style={styles.codeBlock}><Text style={styles.codeText}>{`{\n  "event": "employee.updated",\n  "employeeId": "EMP-2026-001",\n  "attempt": ${state.webhookAttempts + 1},\n  "demo": true\n}`}</Text></View>{persona?.role === 'admin' ? <Button label="Simulate local delivery" icon={Webhook} onPress={simulateWebhook} /> : <Badge label="Administrator action" tone="neutral" />}</Card></View>
    {persona?.role === 'finance' ? <Card style={styles.pad}><SectionHeader title="Government submission simulator" subtitle="Create a fictional reference only after demonstrating output generation." /><View style={styles.govRow}><View style={{ flex: 1 }}><Text style={styles.connectorTitle}>BIR / SSS / PhilHealth / Pag-IBIG demo package</Text><Text style={styles.muted}>No portal credentials, endpoint, or submission schema is used.</Text></View><Button label="Simulate Government Submission" icon={Send} onPress={simulateGovernmentSubmission} /></View>{state.submissionReferences.map((ref) => <View key={ref} style={styles.ref}><Check size={15} color={colors.green} /><Text style={styles.refText}>{ref} · FICTIONAL REFERENCE</Text></View>)}</Card> : null}
  </>;
}

export function AdministrationScreen() {
  const { state } = useDemo();
  const [tab, setTab] = useState<'Audit trail' | 'Demo Outbox' | 'Seeded accounts' | 'Demo information'>('Audit trail');
  return <>
    <View style={styles.stats}><StatCard label="Audit events" value={String(state.audit.length)} detail="Runtime-local evidence" icon={ShieldCheck} /><StatCard label="Outbox items" value={String(state.outbox.length)} detail="Simulated delivery only" icon={Mail} tone="info" /><StatCard label="Seeded accounts" value={String(personas.length)} detail="Separate login personas" icon={Settings} tone="success" /><StatCard label="Acceptance coverage" value="Automated" detail="Run npm run acceptance" icon={Check} tone="success" /></View>
    <Card><View style={styles.tabBar}><SelectChips options={['Audit trail', 'Demo Outbox', 'Seeded accounts', 'Demo information'] as const} value={tab} onChange={setTab} /></View>
      {tab === 'Audit trail' ? <Table headers={['Timestamp', 'Actor', 'Action', 'Area', 'Detail']} rows={state.audit.slice(0, 40).map((event) => [event.at.replace('T', ' ').slice(0, 16), event.actor, <Badge label={event.action} tone={event.action === 'Approved' || event.action === 'Released' ? 'success' : 'info'} />, event.area, event.detail])} /> : null}
      {tab === 'Demo Outbox' ? <Table headers={['Timestamp', 'Channel', 'Recipient', 'Subject', 'Status']} rows={state.outbox.slice(0, 40).map((item) => [item.at.replace('T', ' ').slice(0, 16), item.channel, item.recipient, item.subject, <Badge label={item.status} tone={item.status === 'Simulated delivered' ? 'success' : 'danger'} />])} /> : null}
      {tab === 'Seeded accounts' ? <Table headers={['Persona', 'Email', 'Shared password', 'Demonstrates']} rows={personas.map((item) => [<View><Text style={styles.connectorTitle}>{item.title}</Text><Text style={styles.muted}>{item.initials}</Text></View>, item.email, DEMO_PASSWORD, item.description])} /> : null}
      {tab === 'Demo information' ? <View style={styles.info}><View style={styles.infoHero}><DatabaseZap size={28} color={colors.blue} /><View><Text style={styles.infoTitle}>ZylHR Client Demo</Text><Text style={styles.muted}>{SEED_VERSION} · Demo date {DEMO_DATE} · Asia/Manila</Text></View></View>{[
        ['Data lifetime', 'All mutable data stays only in this browser runtime. Sign-out keeps it; reload discards it.'], ['Isolation', 'Every tab or separately opened instance receives its own independent deterministic seed.'], ['Runtime services', 'No backend API, database, localStorage, IndexedDB, cloud account, or remote data service is used.'], ['Truth claim', 'This is a functional product demonstration, not a production HRIS or certified payroll system.'], ['Fictional data', 'Every person, organization, identifier, account, document, and payroll value is fictional.'],
      ].map(([label, body]) => <View key={label} style={styles.infoRow}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoBody}>{body}</Text></View>)}<Card style={styles.acceptanceCard}><Text style={styles.connectorTitle}>Automated acceptance evidence</Text><Text style={styles.muted}>The deterministic harness covers seed counts, role-scoped search, work queues, historical reconstruction, document scenarios, CSV validation fixtures, payroll snapshots, variance/reconciliation controls, leave-to-payroll flow, XLSX structure and demo labels, and the absence of runtime network/persistence APIs.</Text><Text style={styles.command}>npm run acceptance</Text></Card></View> : null}
    </Card>
  </>;
}

const styles = StyleSheet.create({
  notice: { padding: 14, flexDirection: 'row', alignItems: 'center', gap: 11, backgroundColor: colors.blueSoft, borderColor: '#D1E0FF' }, noticeTitle: { color: colors.blueDark, fontSize: 12, fontWeight: '900' }, muted: { color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 3 }, stats: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, connectorGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, connector: { minWidth: 210, flex: 1, padding: 15, gap: 8 }, connectorIcon: { width: 36, height: 36, borderRadius: 8, backgroundColor: colors.blueSoft, alignItems: 'center', justifyContent: 'center' }, connectorTitle: { color: colors.ink, fontSize: 12, fontWeight: '900' }, twoCol: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 }, pad: { minWidth: 300, flex: 1, padding: 18, gap: 14 }, codeBlock: { backgroundColor: colors.ink, borderRadius: radii.md, padding: 14 }, codeText: { color: '#DCE6FF', fontFamily: 'monospace', fontSize: 10, lineHeight: 17 }, govRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 12 }, ref: { padding: 10, borderRadius: radii.md, backgroundColor: colors.greenSoft, flexDirection: 'row', alignItems: 'center', gap: 8 }, refText: { color: colors.green, fontSize: 10, fontWeight: '800' }, tabBar: { padding: 14, borderBottomWidth: 1, borderColor: colors.border }, info: { padding: 22, gap: 4 }, infoHero: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingBottom: 16 }, infoTitle: { color: colors.ink, fontSize: 18, fontWeight: '900' }, infoRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 14, paddingVertical: 13, borderTopWidth: 1, borderColor: colors.border }, infoLabel: { width: 150, color: colors.text, fontSize: 11, fontWeight: '800' }, infoBody: { minWidth: 220, flex: 1, color: colors.muted, fontSize: 11, lineHeight: 17 }, acceptanceCard: { padding: 15, gap: 8, marginTop: 12, backgroundColor: colors.greenSoft, borderColor: '#ABEFC6' }, command: { alignSelf: 'flex-start', marginTop: 5, paddingHorizontal: 10, paddingVertical: 7, borderRadius: radii.md, color: '#fff', backgroundColor: colors.ink, fontSize: 10, fontFamily: 'monospace' },
});
