import React, { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Building2, Edit3, FileUp, Plus, Search, UserPlus, UsersRound } from 'lucide-react-native';
import { Badge, Button, Card, Dialog, EmptyState, Field, SectionHeader, SelectChips, StatCard, Table } from '../components/ui';
import { colors, money, radii } from '../theme';
import { Employee, EmployeeStatus, OrganizationRecord } from '../types';
import { useDemo } from '../store/DemoStore';
import { HistoricalAsOfPanel } from './DemoPlusScreens';

const statusTone = (status: EmployeeStatus) => status === 'Active' ? 'success' : status === 'Draft' ? 'warning' : 'neutral';

export function OrganizationScreen() {
  const { state, persona, addOrganization, updateOrganization, deleteOrganization, toggleOrganization } = useDemo();
  const [open, setOpen] = useState(false);
  const [view, setView] = useState<'List' | 'Hierarchy' | 'Historical as-of'>('List');
  const [editing, setEditing] = useState<OrganizationRecord | null>(null);
  const [type, setType] = useState<'Department' | 'Position' | 'Cost center'>('Department');
  const [name, setName] = useState('');
  const [parent, setParent] = useState('ZylWorks Group');
  const groups = (['Entity', 'Branch', 'Department', 'Position', 'Cost center'] as const).map((group) => ({ group, records: state.organization.filter((item) => item.type === group) }));
  const startCreate = () => { setEditing(null); setType('Department'); setName(''); setParent('ZylWorks Group'); setOpen(true); };
  const startEdit = (record: OrganizationRecord) => { setEditing(record); setType(record.type === 'Position' || record.type === 'Cost center' ? record.type : 'Department'); setName(record.name); setParent(record.parent ?? 'ZylWorks Group'); setOpen(true); };
  return <>
    <View style={styles.stats}><StatCard label="Legal entities" value="2" detail="Under ZylWorks Group" icon={Building2} /><StatCard label="Branches" value="3" detail="Manila, Cebu, Davao" icon={Building2} tone="success" /><StatCard label="Departments" value={String(state.organization.filter((item) => item.type === 'Department').length)} detail="Live employee counts" icon={UsersRound} tone="warning" /><StatCard label="Positions" value={String(state.organization.filter((item) => item.type === 'Position').length)} detail="Across five levels" icon={UsersRound} /></View>
    <Card><View style={styles.cardPad}><SectionHeader title="Organization hierarchy" subtitle="Referenced records cannot be deleted or deactivated. Counts use the live runtime store." action={persona?.role === 'admin' ? <Button label="Add record" icon={Plus} compact onPress={startCreate} /> : <Badge label="View only for this persona" tone="neutral" />} /><SelectChips options={['List', 'Hierarchy', 'Historical as-of'] as const} value={view} onChange={setView} /></View>
      {view === 'List' ? <Table headers={['Type / name', 'Parent', 'Employees', 'Status', 'Actions']} rows={groups.flatMap(({ group, records }) => records.map((record) => [
        <View><Text style={styles.primary}>{record.name}</Text><Text style={styles.secondary}>{group} · {record.id}</Text></View>, record.parent ?? 'ZylWorks Group', String(state.employees.filter((employee) => [employee.entity, employee.branch, employee.department, employee.position].includes(record.name)).length), <Badge label={record.active ? 'Active' : 'Inactive'} tone={record.active ? 'success' : 'neutral'} />,
        persona?.role === 'admin' ? <View style={styles.inlineActions}><Button label="Edit" tone="secondary" compact onPress={() => startEdit(record)} /><Button label={record.active ? 'Deactivate' : 'Activate'} tone="secondary" compact onPress={() => toggleOrganization(record.id)} /><Button label="Delete" tone="danger" compact onPress={() => deleteOrganization(record.id)} /></View> : '—',
      ]))} /> : view === 'Hierarchy' ? <View style={styles.hierarchy}><View style={styles.groupRoot}><Text style={styles.groupRootTitle}>ZylWorks Group</Text><Text style={[styles.secondary, { color: '#CBD5E1' }]}>{state.employees.filter((employee) => employee.status === 'Active').length} active employees</Text></View><View style={styles.hierarchyGrid}>{state.organization.filter((item) => item.type === 'Entity').map((entity) => <Card key={entity.id} style={styles.entityCard}><Text style={styles.primary}>{entity.name}</Text><Text style={styles.secondary}>{state.employees.filter((employee) => employee.entity === entity.name && employee.status === 'Active').length} employees</Text><View style={styles.childList}>{state.organization.filter((item) => item.type === 'Branch' && item.parent === entity.name).map((branch) => <View key={branch.id} style={styles.childRow}><Building2 size={14} color={colors.blue} /><View><Text style={styles.childTitle}>{branch.name}</Text><Text style={styles.secondary}>{state.employees.filter((employee) => employee.branch === branch.name && employee.status === 'Active').length} employees</Text></View></View>)}</View></Card>)}</View><View style={styles.departmentGrid}>{state.organization.filter((item) => item.type === 'Department').map((department) => <View key={department.id} style={styles.departmentNode}><Text style={styles.primary}>{department.name}</Text><Text style={styles.secondary}>{state.employees.filter((employee) => employee.department === department.name && employee.status === 'Active').length} employees · {state.organization.filter((item) => item.type === 'Position' && item.parent === department.name).length} positions</Text></View>)}</View></View> : <View style={styles.cardPad}><HistoricalAsOfPanel /></View>}
    </Card>
    <Dialog visible={open} title={editing ? `Edit ${editing.type}` : 'Create organization record'} subtitle="This change lasts only for the current browser runtime." onClose={() => setOpen(false)}><SelectChips label="Record type" options={['Department', 'Position', 'Cost center'] as const} value={type} onChange={setType} /><Field label="Name" value={name} onChangeText={setName} placeholder="e.g. Client Success" /><Field label="Parent" value={parent} onChangeText={setParent} placeholder="ZylWorks Group" /><View style={styles.actions}><Button label="Cancel" tone="secondary" onPress={() => setOpen(false)} /><Button label={editing ? 'Save changes' : 'Create record'} onPress={() => { const saved = editing ? updateOrganization(editing.id, name, parent) : addOrganization(type, name, parent); if (saved) { setEditing(null); setOpen(false); } }} /></View></Dialog>
  </>;
}

export function PeopleScreen() {
  const { state, persona, addEmployee, activateEmployee, updateEmployeeSalary, updateEmployeeAssignment, applyEmploymentAction, addTemporaryUpload } = useDemo();
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState<'All' | EmployeeStatus>('All');
  const [departmentFilter, setDepartmentFilter] = useState('All departments');
  const [sort, setSort] = useState<'Name' | 'Employee ID' | 'Department'>('Name');
  const [page, setPage] = useState(1);
  const [profile, setProfile] = useState<Employee | null>(null);
  const [addOpen, setAddOpen] = useState(false);
  const [actionOpen, setActionOpen] = useState(false);
  const [salary, setSalary] = useState('');
  const [assignment, setAssignment] = useState({ department: '', position: '' });
  const [actionForm, setActionForm] = useState({ type: 'Transfer' as 'Transfer' | 'Promotion' | 'Compensation change' | 'Regularization' | 'Separation', effectiveDate: '2026-08-16', reason: '', detail: '' });
  const [form, setForm] = useState({ firstName: '', lastName: '', department: 'Information Technology', position: 'Software Engineer' });
  const scoped = useMemo(() => {
    let employees = state.employees;
    if (persona?.role === 'employee') employees = employees.filter((employee) => employee.id === persona.employeeId);
    if (persona?.role === 'manager') employees = employees.filter((employee) => employee.managerId === persona.employeeId);
    if (persona?.role === 'recruiter') employees = employees.filter((employee) => employee.status === 'Draft');
    const query = search.trim().toLowerCase();
    const filtered = employees.filter((employee) => (status === 'All' || employee.status === status) && (departmentFilter === 'All departments' || employee.department === departmentFilter) && (!query || `${employee.firstName} ${employee.lastName} ${employee.id} ${employee.department}`.toLowerCase().includes(query)));
    return [...filtered].sort((a, b) => sort === 'Employee ID' ? a.employeeNo.localeCompare(b.employeeNo) : sort === 'Department' ? a.department.localeCompare(b.department) || a.lastName.localeCompare(b.lastName) : a.lastName.localeCompare(b.lastName) || a.firstName.localeCompare(b.firstName));
  }, [state.employees, persona, search, status, departmentFilter, sort]);
  const pageSize = 15;
  const pageCount = Math.max(1, Math.ceil(scoped.length / pageSize));
  const currentPage = Math.min(page, pageCount);
  const shown = scoped.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  const canSeePay = persona && ['hr', 'payroll', 'payrollapprover', 'finance', 'employee'].includes(persona.role);
  const selectTemporaryFile = () => {
    if (!profile || typeof document === 'undefined') return;
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.pdf,.png,.jpg,.jpeg,.doc,.docx';
    input.onchange = () => {
      const file = input.files?.[0];
      if (file) addTemporaryUpload(profile.id, file.name, file.size);
    };
    input.click();
  };
  return <>
    <View style={styles.toolbar}><View style={styles.searchBox}><Search size={16} color={colors.muted} /><Field value={search} onChangeText={(value) => { setSearch(value); setPage(1); }} placeholder="Search name, ID, or department…" /></View>{persona?.role === 'hr' ? <Button label="Add employee" icon={UserPlus} onPress={() => setAddOpen(true)} /> : null}</View>
    <Card><View style={styles.filterPad}><SelectChips options={['All', 'Active', 'Draft', 'Separated'] as const} value={status} onChange={(value) => { setStatus(value); setPage(1); }} /><SelectChips options={['All departments', ...state.organization.filter((item) => item.type === 'Department').map((item) => item.name)]} value={departmentFilter} onChange={(value) => { setDepartmentFilter(value); setPage(1); }} /><SelectChips options={['Name', 'Employee ID', 'Department'] as const} value={sort} onChange={setSort} /><Text style={styles.resultText}>{scoped.length} result{scoped.length === 1 ? '' : 's'} · Page {currentPage}/{pageCount}</Text></View>
      {shown.length ? <Table headers={['Employee', 'Position', 'Department', 'Location', 'Payroll group', 'Status']} rows={shown.map((employee) => [
        <Pressable onPress={() => { setProfile(employee); setSalary(String(employee.salaryCents / 100)); setAssignment({ department: employee.department, position: employee.position }); }}><Text style={[styles.primary, { color: colors.blue }]}>{employee.firstName} {employee.lastName}</Text><Text style={styles.secondary}>{employee.id} · {employee.email}</Text></Pressable>,
        employee.position, employee.department, employee.branch, employee.payrollGroup, <Badge label={employee.status} tone={statusTone(employee.status)} />,
      ])} /> : <EmptyState icon={UsersRound} title="No employees match" body="Change the search or status filter. Access scope is also applied for this persona." />}<View style={styles.pagination}><Button label="Previous" tone="secondary" compact disabled={currentPage <= 1} onPress={() => setPage(Math.max(1, currentPage - 1))} /><Text style={styles.resultText}>Showing {(currentPage - 1) * pageSize + (shown.length ? 1 : 0)}–{(currentPage - 1) * pageSize + shown.length} of {scoped.length}</Text><Button label="Next" tone="secondary" compact disabled={currentPage >= pageCount} onPress={() => setPage(Math.min(pageCount, currentPage + 1))} /></View>
    </Card>
    <Dialog visible={!!profile} title={profile ? `${profile.firstName} ${profile.lastName}` : 'Employee'} subtitle={profile ? `${profile.id} · Fictional connected employee record` : ''} onClose={() => setProfile(null)} width={720}>
      {profile ? <><View style={styles.profileHero}><View style={styles.profileAvatar}><Text style={styles.profileInitials}>{profile.firstName[0]}{profile.lastName[0]}</Text></View><View style={{ flex: 1 }}><Text style={styles.profileName}>{profile.position}</Text><Text style={styles.secondary}>{profile.department} · {profile.branch}</Text></View><Badge label={profile.status} tone={statusTone(profile.status)} /></View>
      <View style={styles.detailGrid}>{[
        ['Employment', profile.employmentType], ['Entity', profile.entity], ['Schedule', profile.schedule], ['Payroll group', profile.payrollGroup], ['Hire date', profile.hireDate], ['Leave balance', `${profile.leaveBalance} days`],
      ].map(([label, value]) => <View key={label} style={styles.detail}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>)}</View>
      {canSeePay ? <Card style={styles.innerCard}><SectionHeader title="Compensation & protected identifiers" subtitle="Sensitive identifiers remain masked on screen." /><View style={styles.detailGrid}><View style={styles.detail}><Text style={styles.detailLabel}>Pay basis</Text><Text style={styles.detailValue}>{profile.payBasis}</Text></View><View style={styles.detail}><Text style={styles.detailLabel}>Current rate</Text><Text style={styles.detailValue}>{money(profile.salaryCents)}</Text></View><View style={styles.detail}><Text style={styles.detailLabel}>Bank</Text><Text style={styles.detailValue}>•••• {profile.bankAccount.slice(-4)}</Text></View><View style={styles.detail}><Text style={styles.detailLabel}>Government ID</Text><Text style={styles.detailValue}>•••• {profile.governmentId.slice(-4)}</Text></View></View></Card> : <Card style={styles.restricted}><Text style={styles.restrictedTitle}>Compensation is hidden for this persona</Text><Text style={styles.secondary}>The route and data-access scope both enforce the demo permission matrix.</Text></Card>}
      <Card style={styles.innerCard}><SectionHeader title="Contracts & documents" subtitle="Seeded records plus temporary browser-local selections." action={persona?.role === 'hr' || persona?.employeeId === profile.id ? <Button label="Select temporary file" icon={FileUp} tone="secondary" compact onPress={selectTemporaryFile} /> : undefined} /><View style={styles.document}><View><Text style={styles.primary}>Employment contract · DEMO</Text><Text style={styles.secondary}>Signed fixture · expires none · fictional preview</Text></View><Badge label="Current" tone="success" /></View>{state.temporaryUploads.filter((upload) => upload.employeeId === profile.id).map((upload) => <View key={upload.id} style={styles.document}><View><Text style={styles.primary}>{upload.name}</Text><Text style={styles.secondary}>{Math.max(1, Math.round(upload.size / 1024))} KB · selected locally · never transmitted</Text></View><Badge label="Temporary" tone="warning" /></View>)}</Card>
      {(persona?.role === 'hr' || persona?.role === 'admin') ? <Card style={styles.innerCard}><SectionHeader title="Organization assignment" subtitle="Uses active reference records and updates live counts." /><View style={styles.formRow}><SelectChips label="Department" options={state.organization.filter((item) => item.type === 'Department' && item.active).map((item) => item.name)} value={assignment.department} onChange={(department) => setAssignment({ ...assignment, department })} /><SelectChips label="Position" options={state.organization.filter((item) => item.type === 'Position' && item.active).map((item) => item.name)} value={assignment.position} onChange={(position) => setAssignment({ ...assignment, position })} /></View><View style={styles.actions}><Button label="Save assignment" onPress={() => { if (updateEmployeeAssignment(profile.id, assignment.department, assignment.position)) setProfile({ ...profile, ...assignment }); }} /></View></Card> : null}
      <Card style={styles.innerCard}><SectionHeader title="Employment history" subtitle="Effective-dated actions remain traceable." action={persona?.role === 'hr' ? <Button label="Record HR action" icon={Plus} tone="secondary" compact onPress={() => setActionOpen(true)} /> : undefined} />{profile.employmentHistory.map((item) => <View key={item.id} style={styles.document}><View><Text style={styles.primary}>{item.type} · {item.effectiveDate}</Text><Text style={styles.secondary}>{item.detail} · {item.reason}</Text></View></View>)}</Card>
      {persona?.role === 'hr' ? <View style={styles.editBlock}><Field label="Monthly / daily / hourly rate (PHP)" value={salary} onChangeText={setSalary} keyboardType="numeric" /><Button label="Save compensation" icon={Edit3} onPress={() => { if (updateEmployeeSalary(profile.id, Math.round(Number(salary) * 100))) setProfile({ ...profile, salaryCents: Math.round(Number(salary) * 100) }); }} />{profile.status === 'Draft' ? <Button label="Activate employee" tone="secondary" onPress={() => { if (activateEmployee(profile.id)) setProfile(null); }} /> : null}</View> : null}
      </> : null}
    </Dialog>
    <Dialog visible={actionOpen} title={profile ? `Record action · ${profile.firstName} ${profile.lastName}` : 'Record employment action'} subtitle="Actions are effective-dated and appended to employment history." onClose={() => setActionOpen(false)}><SelectChips label="Action" options={['Transfer', 'Promotion', 'Compensation change', 'Regularization', 'Separation'] as const} value={actionForm.type} onChange={(type) => setActionForm({ ...actionForm, type })} /><Field label="Effective date" value={actionForm.effectiveDate} onChangeText={(effectiveDate) => setActionForm({ ...actionForm, effectiveDate })} /><Field label="Reason" value={actionForm.reason} onChangeText={(reason) => setActionForm({ ...actionForm, reason })} placeholder="Required business reason" /><Field label="Action detail" value={actionForm.detail} onChangeText={(detail) => setActionForm({ ...actionForm, detail })} placeholder="New title, location, or change summary" /><View style={styles.actions}><Button label="Cancel" tone="secondary" onPress={() => setActionOpen(false)} /><Button label="Record action" onPress={() => { if (profile && applyEmploymentAction(profile.id, actionForm.type, actionForm.effectiveDate, actionForm.reason, actionForm.detail)) { setActionOpen(false); setProfile(null); } }} /></View></Dialog>
    <Dialog visible={addOpen} title="Create employee draft" subtitle="HR must review setup before activation." onClose={() => setAddOpen(false)}><View style={styles.formRow}><Field label="First name" value={form.firstName} onChangeText={(firstName) => setForm({ ...form, firstName })} /><Field label="Last name" value={form.lastName} onChangeText={(lastName) => setForm({ ...form, lastName })} /></View><Field label="Department" value={form.department} onChangeText={(department) => setForm({ ...form, department })} /><Field label="Position" value={form.position} onChangeText={(position) => setForm({ ...form, position })} /><View style={styles.actions}><Button label="Cancel" tone="secondary" onPress={() => setAddOpen(false)} /><Button label="Create draft" icon={Plus} onPress={() => { if (addEmployee(form)) { setAddOpen(false); setForm({ firstName: '', lastName: '', department: 'Information Technology', position: 'Software Engineer' }); } }} /></View></Dialog>
  </>;
}

const styles = StyleSheet.create({
  stats: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, cardPad: { padding: 18 }, primary: { color: colors.text, fontSize: 12, fontWeight: '800' }, secondary: { color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 2 }, actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8, marginTop: 4 }, toolbar: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: 12 }, searchBox: { minWidth: 270, maxWidth: 540, flex: 1, flexDirection: 'row', alignItems: 'center', gap: 7 }, filterPad: { padding: 14, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderColor: colors.border }, resultText: { color: colors.muted, fontSize: 10 }, profileHero: { flexDirection: 'row', alignItems: 'center', gap: 12 }, profileAvatar: { width: 52, height: 52, borderRadius: 26, backgroundColor: colors.ink, alignItems: 'center', justifyContent: 'center' }, profileInitials: { color: '#fff', fontSize: 16, fontWeight: '900' }, profileName: { color: colors.ink, fontSize: 15, fontWeight: '800' }, detailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, detail: { minWidth: 150, flex: 1, padding: 12, borderRadius: radii.md, backgroundColor: colors.surfaceAlt }, detailLabel: { color: colors.muted, fontSize: 9, fontWeight: '700', textTransform: 'uppercase' }, detailValue: { color: colors.text, fontSize: 12, fontWeight: '700', marginTop: 5 }, innerCard: { padding: 15, gap: 13 }, restricted: { padding: 15, backgroundColor: colors.surfaceAlt }, restrictedTitle: { color: colors.text, fontSize: 12, fontWeight: '800' }, editBlock: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-end', gap: 8, borderTopWidth: 1, borderColor: colors.border, paddingTop: 14 }, formRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  document: { minHeight: 50, paddingVertical: 9, borderTopWidth: 1, borderColor: colors.border, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, pagination: { padding: 12, borderTopWidth: 1, borderColor: colors.border, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 12 }, inlineActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 5 }, hierarchy: { padding: 20, gap: 18 }, groupRoot: { alignSelf: 'center', minWidth: 240, padding: 16, backgroundColor: colors.ink, borderRadius: radii.lg, alignItems: 'center' }, groupRootTitle: { color: '#fff', fontSize: 15, fontWeight: '900' }, hierarchyGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 }, entityCard: { minWidth: 270, flex: 1, padding: 16, gap: 12 }, childList: { gap: 7 }, childRow: { padding: 10, borderRadius: radii.md, backgroundColor: colors.surfaceAlt, flexDirection: 'row', alignItems: 'center', gap: 9 }, childTitle: { color: colors.text, fontSize: 11, fontWeight: '800' }, departmentGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, departmentNode: { minWidth: 190, flex: 1, padding: 12, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, backgroundColor: colors.surface },
});
